name: Triage tasks

on: pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Get Labels
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            const fs = require('fs')

            const json = fs.readFileSync(process.env.GITHUB_EVENT_PATH, { encoding: "utf-8" })
            const event = JSON.parse(json)
            const pull = event.pull_request

            // Get existing labels on PR
            const existingLabels = pull.labels.map(label => label.name)

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Labels: [${existingLabels.toString()}]`
            })
