name: Triage tasks

on: pull_request

jobs:
  get-labels:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.labels.outputs.result }}
    steps:
      - name: Get Labels
        id: labels
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            /*const pull = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })

            // Get existing labels on PR
            return pull.labels.map(label => label.name)*/
            console.log(context)
            console.log("---------------")
            console.log(context.pull_request.labels)
            return context.pull_request.labels.map(label => label.name)

  post-comment:
    needs: get-labels
    runs-on: ubuntu-latest
    steps:
      - name: Post comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            labels = ${{ needs.get-labels.outputs.labels }}
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Labels: [${labels.toString()}]`
            })
