name: Triage tasks

on: pull_request

jobs:
  get-labels:
    runs-on: ubuntu-latest
    outputs:
      ci-syntax-only: ${{ steps.labels.outputs.result }}
    steps:
      - name: Get Labels
        id: labels
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            /*const pull = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })

            // Get existing labels on PR
            return pull.labels.map(label => label.name)*/
            // console.log(context)
            // console.log("---------------")
            // console.log(context.payload.pull_request.labels)

            const labels =  context.payload.pull_request.labels.map(label => label.name)
            console.log(`Labels: ${labels.toString()}`)
            console.log(labels.includes('enhancement'))
            return labels.includes('enhancement')

  post-comment:
    needs: get-labels
    runs-on: ubuntu-latest
    if: needs.get-labels.outputs.ci-syntax-only
    steps:
      - name: Post comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(${{ needs.get-labels.outputs.ci-syntax-only }})
            labels = ${{ needs.get-labels.outputs.labels }}
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'enhancement not applied'
            })
