name: Triage tasks

on: pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Get Labels
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            const github1 = require('@actions/github')

            const token = core.getInput("github-token", { required: true })

            const client = github1.getOctokit(token)

            const pull = await client.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })

            // Get existing labels on PR
            const existingLabels = pull.labels.map(label => label.name)

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Labels: [${existingLabels.toString()}]`
            })
