name: Triage tasks

on:
  push:
    branches: main
  pull_request:

jobs:
  get-labels:
    runs-on: ubuntu-latest
    outputs:
      run-tests: ${{ steps.labels.outputs.result }}
    steps:
      - name: Get Labels
        id: labels
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { labels: labels } } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            if (!labels.map(label => label.name).includes('CI-syntax-only')) {
              console.log('No CI-syntax-only label found. Running tests.')
              return true
            }
            console.log('CI-syntax-only label found. Skipping tests.')

  post-comment:
    needs: get-labels
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && needs.get-labels.outputs.run-tests
    steps:
      - name: Post comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(${{ needs.get-labels.outputs.run-tests }})
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'enhancement not applied: running tests'
            })
